server:
  port: 9080
logging:
  level:
    org.springframework.web: DEBUG
spring:
  datasource:
    url: jdbc:h2:./.local-db/todos;DB_CLOSE_DELAY=-1;MODE=DB2;AUTO_SERVER=TRUE
    username: sa
    password: null
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  jackson:
    deserialization:
      fail-on-unknown-properties: true
springdoc:
  api-docs:
    path: /api-docs
